"""Contact route enricher for resolved companies."""

from __future__ import annotations

import re
from typing import Any
from urllib.parse import urlparse
from uuid import UUID, uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from config.enums import ContactRouteType
from db.models.contact_route import ContactRoute as DBContactRoute

_EMAIL_RE = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
_PHONE_RE = re.compile(r"[+\d][\d\s().-]{5,}\d")
_URL_RE = re.compile(r"https?://[^\s<>\"{}|\\^`\[\]]+")

_NAV_LABELS = {
    "about",
    "call",
    "call now",
    "call today",
    "ceiling fans",
    "click here",
    "contact",
    "contact me",
    "contact our team",
    "contact us",
    "details",
    "email us",
    "follow",
    "free quote",
    "get a quote",
    "get in touch",
    "learn more",
    "link",
    "menu",
    "navigation",
    "page",
    "plumber bulimba",
    "quick links",
    "quicklinks",
    "read bio",
    "read more",
    "request a quote",
    "roof restoration",
    "send a message",
    "send message",
    "send us a message",
    "sitemap",
    "this week",
    "use",
    "visit",
    "web design",
    "website",
}

_GENERIC_NAME_WORDS = {
    "about",
    "account",
    "accountant",
    "accountants",
    "accounting",
    "accounts",
    "acreage",
    "actuaries",
    "address",
    "addresses",
    "admin",
    "administrator",
    "adult",
    "advice",
    "adviser",
    "advisers",
    "advisor",
    "advisors",
    "advisory",
    "affiliates",
    "agency",
    "agent",
    "air",
    "all",
    "alley",
    "analysts",
    "answers",
    "apartment",
    "applicants",
    "application",
    "applications",
    "apply",
    "appraisal",
    "appraisers",
    "arcade",
    "architects",
    "archive",
    "area",
    "areas",
    "articles",
    "assessors",
    "asset",
    "assets",
    "assistants",
    "associates",
    "attach",
    "attorney",
    "au",
    "auckland",
    "auction",
    "auctions",
    "auditors",
    "australia",
    "australian",
    "available",
    "ave",
    "avenue",
    "background",
    "bad",
    "bank",
    "banking",
    "barrister",
    "bay",
    "beach",
    "belimba",
    "beneficiaries",
    "billing",
    "biz",
    "blog",
    "blvd",
    "board",
    "book",
    "booking",
    "bookings",
    "bookkeeper",
    "bookkeepers",
    "bookkeeping",
    "borrowing",
    "boulevard",
    "box",
    "branch",
    "branches",
    "bricklayers",
    "broker",
    "brokerage",
    "brokers",
    "builders",
    "building",
    "bulimba",
    "bulli",
    "business",
    "businesses",
    "buyer",
    "buyers",
    "buying",
    "bvd",
    "by",
    "calculator",
    "call",
    "canberra",
    "candidate",
    "candidates",
    "capital",
    "care",
    "career",
    "careers",
    "carpenters",
    "cart",
    "cash",
    "cashiers",
    "categories",
    "category",
    "cavill",
    "ceiling",
    "center",
    "centre",
    "certified",
    "chat",
    "checkout",
    "child",
    "choose",
    "christchurch",
    "circuit",
    "city",
    "claimants",
    "cleaners",
    "clerk",
    "clerks",
    "click",
    "client",
    "clients",
    "close",
    "club",
    "co",
    "coast",
    "coastal",
    "code",
    "com",
    "commercial",
    "committee",
    "community",
    "company",
    "complete",
    "complex",
    "compliance",
    "component",
    "compromise",
    "concreters",
    "condition",
    "conditioning",
    "conditions",
    "connect",
    "connected",
    "connectors",
    "consolidation",
    "construction",
    "consultancy",
    "consultant",
    "consultants",
    "consultation",
    "consulting",
    "contact",
    "contractor",
    "contractors",
    "conveyancing",
    "cookie",
    "cookies",
    "coordinators",
    "corp",
    "corporate",
    "court",
    "cove",
    "credentials",
    "credit",
    "creek",
    "cres",
    "crescent",
    "crossing",
    "crt",
    "current",
    "customer",
    "customers",
    "date",
    "dates",
    "deceased",
    "demo",
    "department",
    "departments",
    "deposit",
    "depreciation",
    "derivative",
    "design",
    "designers",
    "details",
    "developers",
    "development",
    "diligence",
    "director",
    "directors",
    "disability",
    "disclaimer",
    "discount",
    "discover",
    "dispute",
    "district",
    "do",
    "document",
    "documents",
    "download",
    "downloads",
    "drive",
    "drivers",
    "due",
    "duty",
    "east",
    "easy",
    "ebook",
    "economists",
    "electric",
    "electrical",
    "electrician",
    "electricians",
    "eligible",
    "email",
    "emails",
    "employed",
    "empower",
    "energy",
    "engineering",
    "engineers",
    "enquire",
    "enquiries",
    "enquiry",
    "entrant",
    "entrants",
    "environment",
    "equipment",
    "error",
    "esplanade",
    "estate",
    "estates",
    "etp",
    "evaporative",
    "event",
    "events",
    "example",
    "exchange",
    "executives",
    "experience",
    "expert",
    "expertise",
    "experts",
    "express",
    "facebook",
    "family",
    "fans",
    "faq",
    "faqs",
    "farm",
    "farming",
    "fb",
    "featured",
    "features",
    "feedback",
    "files",
    "final",
    "finance",
    "finances",
    "financial",
    "financing",
    "finder",
    "findings",
    "firm",
    "first",
    "flow",
    "follow",
    "footer",
    "for",
    "foreshore",
    "forex",
    "form",
    "forms",
    "forth",
    "forthcoming",
    "found",
    "foundation",
    "founders",
    "free",
    "frequency",
    "frequently",
    "friend",
    "full",
    "function",
    "fund",
    "funded",
    "funding",
    "funds",
    "future",
    "gallery",
    "garden",
    "gardeners",
    "gardens",
    "general",
    "get",
    "glaziers",
    "glen",
    "global",
    "glossary",
    "go",
    "governance",
    "gpo",
    "grant",
    "grants",
    "group",
    "growth",
    "guard",
    "guards",
    "guests",
    "guide",
    "guides",
    "gutter",
    "handover",
    "harbor",
    "harbour",
    "have",
    "header",
    "heights",
    "hello",
    "help",
    "here",
    "hidden",
    "high",
    "hill",
    "hills",
    "hiring",
    "history",
    "holdings",
    "holiday",
    "home",
    "homeloan",
    "homeloans",
    "homepage",
    "homes",
    "host",
    "hours",
    "house",
    "housing",
    "hr",
    "hub",
    "human",
    "icon",
    "icons",
    "ig",
    "image",
    "implications",
    "in",
    "inc",
    "index",
    "indigenous",
    "industrial",
    "industry",
    "info",
    "information",
    "inquire",
    "inquiries",
    "inquiry",
    "insight",
    "insights",
    "instagram",
    "installation",
    "insurance",
    "insure",
    "integration",
    "interest",
    "interior",
    "internal",
    "international",
    "intro",
    "introduction",
    "invest",
    "investing",
    "investment",
    "investors",
    "island",
    "it",
    "item",
    "items",
    "job",
    "jobs",
    "join",
    "junction",
    "keyword",
    "knowledge",
    "lake",
    "land",
    "landing",
    "landlord",
    "landlords",
    "landscapers",
    "lane",
    "last",
    "latest",
    "launch",
    "law",
    "lawyers",
    "lead",
    "leaders",
    "leads",
    "learn",
    "lease",
    "leased",
    "leasing",
    "legal",
    "lend",
    "lender",
    "lenders",
    "lending",
    "level",
    "library",
    "licence",
    "license",
    "life",
    "light",
    "lighting",
    "like",
    "limited",
    "line",
    "link",
    "linked",
    "linkedin",
    "links",
    "listing",
    "load",
    "loading",
    "loan",
    "loans",
    "local",
    "location",
    "locations",
    "lodge",
    "login",
    "logo",
    "logout",
    "loop",
    "lower",
    "ltd",
    "made",
    "mail",
    "main",
    "maintenance",
    "mall",
    "manage",
    "managed",
    "management",
    "manager",
    "managers",
    "managing",
    "manuka",
    "market",
    "marketing",
    "marketplace",
    "markets",
    "measurement",
    "mechanics",
    "media",
    "medium",
    "melbourne",
    "member",
    "members",
    "menu",
    "message",
    "messages",
    "method",
    "mobile",
    "money",
    "more",
    "mortgage",
    "mortgages",
    "mortgaging",
    "mount",
    "move",
    "my",
    "name",
    "names",
    "national",
    "nav",
    "navigation",
    "need",
    "network",
    "new",
    "news",
    "newsletter",
    "no",
    "nominees",
    "north",
    "note",
    "notice",
    "now",
    "number",
    "nz",
    "nzhl",
    "occupancy",
    "oceania",
    "of",
    "off",
    "offence",
    "offences",
    "offer",
    "offers",
    "office",
    "officer",
    "officers",
    "offices",
    "old",
    "on",
    "once",
    "one",
    "online",
    "only",
    "open",
    "opening",
    "operations",
    "operator",
    "operators",
    "opportunities",
    "opportunity",
    "option",
    "options",
    "optometry",
    "or",
    "order",
    "orders",
    "other",
    "our",
    "out",
    "overview",
    "owner",
    "owners",
    "pacific",
    "packages",
    "page",
    "pages",
    "paid",
    "painters",
    "painting",
    "parade",
    "paradise",
    "park",
    "parks",
    "part",
    "partner",
    "partners",
    "partnership",
    "passage",
    "path",
    "patients",
    "pay",
    "payable",
    "payment",
    "payments",
    "payroll",
    "pde",
    "pdf",
    "people",
    "per",
    "period",
    "permanent",
    "permission",
    "personal",
    "perth",
    "phone",
    "photo",
    "photos",
    "place",
    "plan",
    "planner",
    "planners",
    "planning",
    "plans",
    "plateau",
    "platform",
    "plaza",
    "please",
    "plumber",
    "plumbers",
    "plumbing",
    "point",
    "policy",
    "popular",
    "port",
    "portfolio",
    "positions",
    "post",
    "posted",
    "posting",
    "power",
    "powered",
    "ppa",
    "practice",
    "practitioners",
    "precinct",
    "preferred",
    "premises",
    "press",
    "previous",
    "price",
    "prices",
    "pricing",
    "primary",
    "principals",
    "privacy",
    "private",
    "process",
    "processing",
    "product",
    "products",
    "professional",
    "professionals",
    "profile",
    "program",
    "programs",
    "progress",
    "project",
    "projects",
    "prom",
    "promenade",
    "promo",
    "promotion",
    "properties",
    "property",
    "pty",
    "public",
    "publications",
    "purchase",
    "purpose",
    "quality",
    "quarter",
    "question",
    "questions",
    "quick",
    "quote",
    "range",
    "rate",
    "rates",
    "rating",
    "ratings",
    "read",
    "reading",
    "ready",
    "real",
    "realestate",
    "realtor",
    "realty",
    "receivable",
    "recent",
    "recently",
    "receptionists",
    "recommended",
    "record",
    "records",
    "recruiting",
    "recruitment",
    "referees",
    "refinancing",
    "register",
    "registers",
    "registration",
    "regulatory",
    "related",
    "releases",
    "rent",
    "rental",
    "rentals",
    "repayment",
    "repayments",
    "report",
    "reports",
    "representatives",
    "request",
    "requests",
    "research",
    "researchers",
    "reserve",
    "residential",
    "residents",
    "resolution",
    "resource",
    "resources",
    "response",
    "restoration",
    "results",
    "retail",
    "retirement",
    "returns",
    "review",
    "reviews",
    "right",
    "rights",
    "risk",
    "river",
    "road",
    "role",
    "roles",
    "roof",
    "roofers",
    "roofing",
    "roxby",
    "rss",
    "rural",
    "safe",
    "safety",
    "sale",
    "sales",
    "san",
    "saving",
    "savings",
    "schedule",
    "schedules",
    "scheme",
    "school",
    "search",
    "secretaries",
    "section",
    "secure",
    "securities",
    "security",
    "select",
    "selected",
    "selection",
    "sellers",
    "send",
    "seo",
    "service",
    "services",
    "session",
    "set",
    "setting",
    "settings",
    "settlements",
    "setup",
    "sexual",
    "share",
    "shared",
    "shareholders",
    "sharing",
    "shop",
    "shore",
    "show",
    "showcase",
    "showroom",
    "sidebar",
    "sign",
    "signin",
    "signup",
    "site",
    "sitemap",
    "size",
    "small",
    "smart",
    "sms",
    "solicitors",
    "solutions",
    "some",
    "sort",
    "source",
    "south",
    "special",
    "specialist",
    "specialists",
    "specific",
    "sponsored",
    "spotlight",
    "st",
    "staff",
    "stage",
    "stakeholders",
    "stamp",
    "state",
    "statement",
    "statements",
    "station",
    "status",
    "stay",
    "stn",
    "storage",
    "store",
    "story",
    "strategists",
    "strategy",
    "streamline",
    "street",
    "student",
    "students",
    "studio",
    "study",
    "subcontractors",
    "subiaco",
    "submit",
    "subscribe",
    "subscription",
    "successful",
    "suisse",
    "suit",
    "suite",
    "summary",
    "super",
    "supervisors",
    "suppliers",
    "support",
    "survey",
    "sustainability",
    "switch",
    "sydney",
    "system",
    "tab",
    "tag",
    "tags",
    "talk",
    "tax",
    "taxation",
    "team",
    "technical",
    "technicians",
    "tellers",
    "tenant",
    "tenants",
    "tennant",
    "terms",
    "terr",
    "terrace",
    "territory",
    "test",
    "testimonials",
    "testing",
    "text",
    "thank",
    "thanks",
    "the",
    "theme",
    "thinking",
    "third",
    "this",
    "thoughts",
    "ticket",
    "tickets",
    "tiktok",
    "tilers",
    "time",
    "tip",
    "tips",
    "title",
    "today",
    "tool",
    "tools",
    "topic",
    "topics",
    "total",
    "touch",
    "tower",
    "town",
    "townhouse",
    "track",
    "tracking",
    "trade",
    "trademark",
    "trades",
    "tradespeople",
    "trail",
    "training",
    "transact",
    "transaction",
    "transport",
    "travel",
    "trial",
    "trust",
    "trustees",
    "try",
    "tt",
    "tutorial",
    "tutorials",
    "twitter",
    "two",
    "type",
    "uk",
    "under",
    "underwriters",
    "unit",
    "unsubscribe",
    "up",
    "upcoming",
    "update",
    "updates",
    "updating",
    "upload",
    "urban",
    "url",
    "us",
    "used",
    "useful",
    "user",
    "users",
    "utility",
    "vacancies",
    "vacate",
    "value",
    "valuers",
    "values",
    "vendor",
    "vendors",
    "venture",
    "venus",
    "version",
    "via",
    "video",
    "videos",
    "vietnamese",
    "view",
    "villa",
    "village",
    "virtual",
    "visit",
    "visitor",
    "visitors",
    "visual",
    "voice",
    "volunteer",
    "waikato",
    "waiting",
    "walk",
    "want",
    "ware",
    "warehouse",
    "warning",
    "watch",
    "waters",
    "wauchope",
    "way",
    "we",
    "wealth",
    "wealthy",
    "web",
    "webinar",
    "week",
    "welcome",
    "wellington",
    "wellness",
    "west",
    "western",
    "what",
    "when",
    "where",
    "which",
    "while",
    "whirlybird",
    "who",
    "why",
    "widget",
    "widgets",
    "wiki",
    "win",
    "windows",
    "with",
    "without",
    "wizard",
    "woonona",
    "workflow",
    "workforce",
    "working",
    "works",
    "workshop",
    "world",
    "worth",
    "write",
    "writer",
    "writing",
    "written",
    "www",
    "xero",
    "xls",
    "xml",
    "year",
    "years",
    "yes",
    "yesterday",
    "yet",
    "you",
    "your",
    "youtube",
    "zealand",
    "zone",
}

_PAGE_LABELS = {
    "account sign",
    "aml compliance",
    "aml compliances",
    "arana hills",
    "areas of expertise",
    "asset register",
    "asset registers",
    "attach files",
    "australian credit licence",
    "australian securities",
    "belimba park",
    "blackshaw manuka",
    "blackshaw queanbeyan",
    "bookings my account sign",
    "borrowing power",
    "bright realty",
    "brighton life",
    "brooke barnes conveyancing clerk",
    "business site",
    "buyer enquiry",
    "camp hill",
    "car loans",
    "career opportunities",
    "cash flow",
    "castle dr",
    "cavill ave",
    "cavill avenue",
    "client portal",
    "client success stories",
    "complete rural conveyancing",
    "condition reports",
    "debt consolidation",
    "deceased estates",
    "director kevin",
    "director steven",
    "director trent",
    "due diligence",
    "dunk insurance",
    "eastwood andrews",
    "eligible entrant",
    "eligible entrants",
    "employed people",
    "error bad",
    "evaporative air conditioning",
    "final thoughts",
    "financing made easy",
    "for sale",
    "foreshore promenade",
    "forthcoming auctions",
    "fox symes",
    "fundwise capital australia",
    "get in touch",
    "gold coast",
    "gpo box",
    "grafton nsw",
    "green gold",
    "gutter guard",
    "have any question",
    "hire equipment",
    "holiday period notice",
    "hunters hill",
    "industry expertise",
    "internal dispute resolution",
    "kimberley address",
    "lameisha langone administration",
    "land size",
    "land sizes",
    "landlord review",
    "last name",
    "loan connectors",
    "loan market",
    "loan refinancing",
    "loan repayment",
    "loan type",
    "log in",
    "log out",
    "login",
    "logout",
    "main menu",
    "managed super funds",
    "managing director",
    "manuka",
    "measurement request",
    "medium businesses",
    "melbourne vic",
    "mgm martin",
    "money quest",
    "mount eliza",
    "my account",
    "my account sign",
    "need some advice",
    "new zealand director",
    "next next third",
    "north sydney",
    "nzhltransact clients",
    "occupancy handover",
    "online cash flow",
    "open homes",
    "opening hours",
    "pay a deposit",
    "pay deposit",
    "payment frequency",
    "permanent disability",
    "phone number",
    "plateau nsw",
    "post code",
    "prd woonona bulli",
    "previous previous",
    "primary sidebar",
    "privacy policy",
    "promotion period",
    "public transport",
    "quick links",
    "racv community foundation",
    "ray white",
    "real-world example",
    "recently lease",
    "recently leased",
    "regional offices",
    "rental appraisal",
    "request measurement",
    "request measurements",
    "research hub",
    "roxby downs",
    "san remo",
    "search enquire",
    "search login",
    "self storage",
    "sexual offences",
    "shore branch",
    "shore branch. discover",
    "sign in",
    "sign out",
    "sign up",
    "stamp duty calculator",
    "stay connected",
    "subiaco",
    "successful ways",
    "surfers paradise",
    "talk with",
    "tax depreciation schedules",
    "tax implications",
    "tenant application",
    "tenant form",
    "tennant creek",
    "the brokerage",
    "the coomera river",
    "the good loan",
    "the lenders club",
    "the loan inspector",
    "the loans analyst",
    "the refinancing process",
    "the wall",
    "this week",
    "upcoming inspections",
    "venus bay",
    "waikato risk advisers",
    "wauchope nsw",
    "wayne hughes consultant",
    "wealthy you",
    "wellness officer",
    "wellness officers",
    "western australia",
    "what we do",
    "whirlybird installation",
    "who is eligible",
    "why choose us",
    "why real",
    "without compromise",
    "woonona bulli",
    "xero set up packages",
    "your information you",
}


def looks_like_html(value: str) -> bool:
    # Detect real HTML/XML tags such as <script>, <span class="x">, </p>, not the
    # angle brackets used in "Name <email>" display forms.
    return (
        bool(re.search(r"<[a-zA-Z][\w-]*(?:\s[^>]*)?/?>", value))
        or "&lt;" in value
        or "&gt;" in value
    )


def extract_email(value: str) -> str | None:
    """Return a syntactically valid email address, extracting it from display forms."""
    if looks_like_html(value):
        return None
    # Decode common URL-encoded spacing that can appear in mailto/display forms.
    value = value.replace("%20", " ")
    # Try "Name <email>" or "Name (title) <email>".
    m = re.search(r"<([^<>]+@[^<>]+)>", value)
    candidate = m.group(1).strip() if m else value.strip()
    # If the candidate still contains spaces, the email is probably the last token.
    if " " in candidate and "@" in candidate:
        parts = [p for p in candidate.split() if "@" in p]
        candidate = parts[-1] if parts else candidate.split()[-1]
    candidate = candidate.lower()
    if not re.fullmatch(r"[\w.+-]+@[\w-]+\.[\w.-]+", candidate):
        return None
    if ".." in candidate or candidate.startswith(".") or candidate.endswith("."):
        return None
    local, _, domain = candidate.partition("@")
    if not local or not domain or "." not in domain.rstrip("."):
        return None
    if domain in ("example.com", "test.com"):
        return None
    return candidate


def extract_phone(value: str) -> str | None:
    """Return a usable phone number extracted from a value or display form."""
    if looks_like_html(value):
        return None
    # Decode common URL-encoded spacing so tel: links render as plain numbers.
    value = value.replace("%20", " ").replace("%2B", "+").replace("%2b", "+")
    m = re.search(r"<([+\d\s().-]+)>", value)
    candidate = m.group(1) if m else value
    # Require at least seven digits.
    digits = re.sub(r"\D", "", candidate)
    if len(digits) < 7:
        return None
    # Prefer the longest phone-like token.
    best: str | None = None
    best_len = 0
    for match in _PHONE_RE.finditer(candidate):
        token = match.group(0).strip()
        token_digits = re.sub(r"\D", "", token)
        if len(token_digits) > best_len:
            best = token
            best_len = len(token_digits)
    return best if best else candidate.strip()


def extract_url(value: str) -> str | None:
    """Return an absolute HTTP(S) URL or reject the value."""
    if looks_like_html(value):
        return None
    m = _URL_RE.search(value)
    if not m:
        return None
    candidate = m.group(0).strip()
    try:
        parsed = urlparse(candidate)
    except ValueError:
        return None
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        return None
    return candidate


def _name_part_is_label(name: str) -> bool:
    """Return True if the name or title text is a page label, not a person."""
    lower = name.strip().lower()
    if not lower:
        return False
    if lower in _NAV_LABELS or lower in _PAGE_LABELS:
        return True
    return any(len(label) > 4 and label in lower for label in (*_NAV_LABELS, *_PAGE_LABELS))


def _is_person_name(name: str) -> bool:
    """Return True if name is a plausible person name."""
    if not name or len(name) > 80 or len(name) < 3:
        return False
    words = name.split()
    if not (2 <= len(words) <= 4):
        return False
    if any(re.search(r"\d", w) for w in words):
        return False
    if "@" in name or "://" in name or "<" in name:
        return False
    return not any(w.lower() in _GENERIC_NAME_WORDS for w in words)


def is_valid_named_contact(value: str) -> bool:
    """Return True if the value represents a real person, not a navigation label."""
    text = value.strip()
    if not text or len(text) > 80:
        return False
    if looks_like_html(text):
        return False
    # Parse "Name (Title)" or "Name".
    m = re.match(r"^(.*?)\s*(?:\((.*)\))?\s*$", text)
    name = m.group(1).strip() if m else text
    title = m.group(2).strip() if m and m.group(2) else ""
    if not name or _name_part_is_label(name):
        return False
    if title and _name_part_is_label(title):
        return False
    return _is_person_name(name)


def _name_in_email_local(name: str, email: str) -> bool:
    """Return True if a name token is plausibly present in the email local part."""
    if "@" not in email:
        return False
    local = email.split("@", 1)[0].lower()
    local_parts = re.split(r"[._\-]", local)
    name_tokens = [w.lower() for w in name.split() if w.isalpha() and len(w) >= 2]
    for token in name_tokens:
        for part in local_parts:
            if len(part) >= 2 and (token in part or part in token):
                return True
            if len(part) == 1 and part == token[0]:
                return True
    return False


def _parse_named_contact_display(value: str) -> dict[str, str] | None:
    """Parse a display string such as 'Name (Title) <contact>' or 'Name - URL'."""
    text = value.strip()
    m = re.match(r"^(.*?)\s*(?:\((.*?)\))?\s*[<-]\s*(.+?)\s*$", text)
    if not m:
        return None
    name = m.group(1).strip()
    title = m.group(2).strip() if m.group(2) else ""
    payload = m.group(3).strip().rstrip(">")
    display_name = f"{name} ({title})" if title else name
    if not is_valid_named_contact(display_name):
        return None
    return {"name": name, "title": title, "value": payload}


def normalize_route_value(route_type: str, value: str) -> str | None:
    """Validate a contact route and return a canonical value, or None to drop it.

    Named contact routes preserve their display form (e.g. "Name <email>") so
    the association between a person and a contact route survives storage.
    """
    if route_type in ("generic_email", "named_work_email_approved"):
        parsed = _parse_named_contact_display(value)
        if parsed:
            email = extract_email(parsed["value"])
            if email:
                if parsed["title"]:
                    return f"{parsed['name']} ({parsed['title']}) <{email}>"
                return f"{parsed['name']} <{email}>"
        email = extract_email(value)
        return email if email else None
    if route_type == "business_phone":
        parsed = _parse_named_contact_display(value)
        if parsed:
            phone = extract_phone(parsed["value"])
            if phone:
                return (
                    f"{parsed['name']} <{phone}>"
                    if not parsed["title"]
                    else f"{parsed['name']} ({parsed['title']}) <{phone}>"
                )
        phone = extract_phone(value)
        return phone if phone else None
    if route_type in ("sales_form", "contact_form", "demo_booking"):
        return extract_url(value)
    if route_type == "named_contact":
        return value if is_valid_named_contact(value) else None
    if route_type == "social_profile_review_only":
        parsed = _parse_named_contact_display(value)
        if parsed:
            url = extract_url(parsed["value"])
            if url:
                return (
                    f"{parsed['name']} - {url}"
                    if not parsed["title"]
                    else f"{parsed['name']} ({parsed['title']}) - {url}"
                )
        url = extract_url(value)
        return url if url else None
    # Unknown route types fall through unchanged.
    return value


def _resolve_route_type(raw_type: str) -> ContactRouteType:
    try:
        return ContactRouteType(raw_type.lower())
    except ValueError:
        return ContactRouteType.GENERIC_EMAIL


async def enrich_contact_routes(
    session: AsyncSession,
    workspace_id: UUID,
    company_id: UUID,
    routes_raw: list[dict[str, Any]],
) -> list[DBContactRoute]:
    """Persist verified contact routes for a resolved company.

    Routes are normalised and validated at the shared boundary: display-form
    emails and phone numbers are extracted to plain addresses, forms require an
    absolute HTTP(S) URL, and named contacts must be real person names, not
    navigation labels or HTML fragments.
    """
    existing = {
        (r.route_type, r.value.lower())
        for r in (
            await session.scalars(
                select(DBContactRoute).where(
                    DBContactRoute.workspace_id == workspace_id,
                    DBContactRoute.company_id == company_id,
                )
            )
        ).all()
    }
    created: list[DBContactRoute] = []
    for route in routes_raw:
        if not isinstance(route, dict):
            continue
        raw_value = str(route.get("value", "")).strip()
        if not raw_value or len(raw_value) > 255:
            continue
        route_type = _resolve_route_type(route.get("type", "generic_email")).value
        value = normalize_route_value(route_type, raw_value)
        if not value:
            continue
        # Only keep named-work-email routes when the email local part actually
        # references the person. Otherwise fall back to a generic company email so
        # we never fabricate a person/email association.
        if route_type == ContactRouteType.NAMED_WORK_EMAIL_APPROVED.value:
            parsed = _parse_named_contact_display(value)
            email = extract_email(parsed["value"]) if parsed else extract_email(value)
            if email:
                name = parsed["name"] if parsed else ""
                if name and _name_in_email_local(name, email):
                    value = email if not parsed else value
                else:
                    route_type = ContactRouteType.GENERIC_EMAIL.value
                    value = email
            else:
                continue
        if (route_type, value.lower()) in existing:
            continue
        existing.add((route_type, value.lower()))
        record = DBContactRoute(
            id=uuid4(),
            workspace_id=workspace_id,
            company_id=company_id,
            route_type=route_type,
            value=value,
            is_verified=bool(route.get("is_verified", False)),
        )
        session.add(record)
        created.append(record)
    await session.flush()
    return created


__all__ = [
    "enrich_contact_routes",
    "extract_email",
    "extract_phone",
    "extract_url",
    "is_valid_named_contact",
    "normalize_route_value",
]
