"""source engine entities

Revision ID: 18caeb93d261
Revises: 4a66035acce6
Create Date: 2026-07-15 23:46:09.287470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18caeb93d261'
down_revision: Union[str, Sequence[str], None] = '4a66035acce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_hit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('source_native_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body_excerpt', sa.Text(), nullable=False),
    sa.Column('company_name_raw', sa.String(length=255), nullable=False),
    sa.Column('company_domain_raw', sa.String(length=255), nullable=False),
    sa.Column('location_raw', sa.String(length=255), nullable=False),
    sa.Column('workplace_type', sa.String(length=255), nullable=False),
    sa.Column('intent_label', sa.String(length=255), nullable=False),
    sa.Column('contact_routes_raw', sa.JSON(), nullable=False),
    sa.Column('raw_snapshot_uri', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('access_policy_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_hit_workspace_id'), 'source_hit', ['workspace_id'], unique=False)
    op.create_table('source_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('source_class', sa.String(length=255), nullable=False),
    sa.Column('access_mode', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('terms_review_status', sa.String(length=255), nullable=False),
    sa.Column('terms_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allowed_outputs', sa.JSON(), nullable=False),
    sa.Column('allowed_fields', sa.JSON(), nullable=False),
    sa.Column('raw_retention_days', sa.Integer(), nullable=False),
    sa.Column('normalized_retention_days', sa.Integer(), nullable=False),
    sa.Column('rate_limit', sa.JSON(), nullable=False),
    sa.Column('kill_switch', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_registry_workspace_id'), 'source_registry', ['workspace_id'], unique=False)
    op.create_table('source_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hits_total', sa.Integer(), nullable=False),
    sa.Column('hits_qualified_total', sa.Integer(), nullable=False),
    sa.Column('hits_duplicate_total', sa.Integer(), nullable=False),
    sa.Column('errors_total', sa.Integer(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_run_campaign_id'), 'source_run', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_source_run_workspace_id'), 'source_run', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_run_workspace_id'), table_name='source_run')
    op.drop_index(op.f('ix_source_run_campaign_id'), table_name='source_run')
    op.drop_table('source_run')
    op.drop_index(op.f('ix_source_registry_workspace_id'), table_name='source_registry')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_source_hit_workspace_id'), table_name='source_hit')
    op.drop_table('source_hit')
    # ### end Alembic commands ###
