"""add source hit content hash unique

Revision ID: 2dee9c0407d9
Revises: f3133807f10f
Create Date: 2026-07-21 02:10:57.112950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dee9c0407d9'
down_revision: Union[str, Sequence[str], None] = 'f3133807f10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM source_hit a
        USING source_hit b
        WHERE a.workspace_id = b.workspace_id
          AND a.source_key = b.source_key
          AND a.content_hash = b.content_hash
          AND a.id > b.id
        """
    )
    op.create_unique_constraint('uq_source_hit_content_hash', 'source_hit', ['workspace_id', 'source_key', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_hit_content_hash', 'source_hit', type_='unique')
    # ### end Alembic commands ###
