"""initial schema

Revision ID: 4a66035acce6
Revises: 
Create Date: 2026-07-15 10:26:27.048886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a66035acce6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_workspace_id'), 'audit_event', ['workspace_id'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('capability_filter', sa.JSON(), nullable=False),
    sa.Column('score_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_workspace_id'), 'campaign', ['workspace_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_workspace_id'), 'company', ['workspace_id'], unique=False)
    op.create_table('jurisdiction_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdiction_policy_workspace_id'), 'jurisdiction_policy', ['workspace_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_index(op.f('ix_membership_workspace_id'), 'membership', ['workspace_id'], unique=False)
    op.create_table('operational_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_metadata_workspace_id'), 'operational_metadata', ['workspace_id'], unique=False)
    op.create_table('page_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('snapshot_path', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_snapshot_workspace_id'), 'page_snapshot', ['workspace_id'], unique=False)
    op.create_table('scorecard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('config_path', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecard_workspace_id'), 'scorecard', ['workspace_id'], unique=False)
    op.create_table('source_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_event_workspace_id'), 'source_event', ['workspace_id'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_workspace_id'), 'source_health', ['workspace_id'], unique=False)
    op.create_table('source_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_policy_workspace_id'), 'source_policy', ['workspace_id'], unique=False)
    op.create_table('ats_board',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('board_url', sa.String(length=2048), nullable=False),
    sa.Column('board_token', sa.String(length=255), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ats_board_company_id'), 'ats_board', ['company_id'], unique=False)
    op.create_index(op.f('ix_ats_board_workspace_id'), 'ats_board', ['workspace_id'], unique=False)
    op.create_table('campaign_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_discovered', sa.Integer(), nullable=False),
    sa.Column('total_qualified', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_run_campaign_id'), 'campaign_run', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_run_workspace_id'), 'campaign_run', ['workspace_id'], unique=False)
    op.create_table('classifier_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('model_provider', sa.String(length=255), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifier_run_company_id'), 'classifier_run', ['company_id'], unique=False)
    op.create_index(op.f('ix_classifier_run_workspace_id'), 'classifier_run', ['workspace_id'], unique=False)
    op.create_table('company_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_alias_company_id'), 'company_alias', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_alias_workspace_id'), 'company_alias', ['workspace_id'], unique=False)
    op.create_table('company_identifier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_identifier_company_id'), 'company_identifier', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_identifier_workspace_id'), 'company_identifier', ['workspace_id'], unique=False)
    op.create_table('company_relationship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('parent_company_id', sa.UUID(), nullable=False),
    sa.Column('child_company_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['child_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['parent_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_relationship_child_company_id'), 'company_relationship', ['child_company_id'], unique=False)
    op.create_index(op.f('ix_company_relationship_parent_company_id'), 'company_relationship', ['parent_company_id'], unique=False)
    op.create_index(op.f('ix_company_relationship_workspace_id'), 'company_relationship', ['workspace_id'], unique=False)
    op.create_table('contact_route',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('route_type', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_route_company_id'), 'contact_route', ['company_id'], unique=False)
    op.create_index(op.f('ix_contact_route_workspace_id'), 'contact_route', ['workspace_id'], unique=False)
    op.create_table('discovery_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('seed_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_event_campaign_id'), 'discovery_event', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_discovery_event_workspace_id'), 'discovery_event', ['workspace_id'], unique=False)
    op.create_table('evidence_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=255), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('extracted_facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_event.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_record_company_id'), 'evidence_record', ['company_id'], unique=False)
    op.create_index(op.f('ix_evidence_record_source_event_id'), 'evidence_record', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_evidence_record_workspace_id'), 'evidence_record', ['workspace_id'], unique=False)
    op.create_table('export_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('lead_ids', sa.JSON(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_record_workspace_id'), 'export_record', ['workspace_id'], unique=False)
    op.create_table('feature',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('feature_value', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_company_id'), 'feature', ['company_id'], unique=False)
    op.create_index(op.f('ix_feature_workspace_id'), 'feature', ['workspace_id'], unique=False)
    op.create_table('lead_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assessment_campaign_id'), 'lead_assessment', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_assessment_company_id'), 'lead_assessment', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_assessment_workspace_id'), 'lead_assessment', ['workspace_id'], unique=False)
    op.create_table('suppression',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_company_id'), 'suppression', ['company_id'], unique=False)
    op.create_index(op.f('ix_suppression_workspace_id'), 'suppression', ['workspace_id'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('campaign_run_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_run_id'], ['campaign_run.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_workspace_id'), 'cost_ledger', ['workspace_id'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('evidence_record_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['evidence_record_id'], ['evidence_record.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_company_id'), 'fact', ['company_id'], unique=False)
    op.create_index(op.f('ix_fact_evidence_record_id'), 'fact', ['evidence_record_id'], unique=False)
    op.create_index(op.f('ix_fact_workspace_id'), 'fact', ['workspace_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('ats_board_id', sa.UUID(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('remote_allowed', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ats_board_id'], ['ats_board.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_ats_board_id'), 'job', ['ats_board_id'], unique=False)
    op.create_index(op.f('ix_job_workspace_id'), 'job', ['workspace_id'], unique=False)
    op.create_table('outcome',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('outcome_type', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_assessment.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_lead_id'), 'outcome', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outcome_workspace_id'), 'outcome', ['workspace_id'], unique=False)
    op.create_table('review_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_assessment.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_assignment_lead_id'), 'review_assignment', ['lead_id'], unique=False)
    op.create_index(op.f('ix_review_assignment_reviewer_id'), 'review_assignment', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_assignment_workspace_id'), 'review_assignment', ['workspace_id'], unique=False)
    op.create_table('review_decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead_assessment.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decision_lead_id'), 'review_decision', ['lead_id'], unique=False)
    op.create_index(op.f('ix_review_decision_reviewer_id'), 'review_decision', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_decision_workspace_id'), 'review_decision', ['workspace_id'], unique=False)
    op.create_table('job_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_history_job_id'), 'job_history', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_history_workspace_id'), 'job_history', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_history_workspace_id'), table_name='job_history')
    op.drop_index(op.f('ix_job_history_job_id'), table_name='job_history')
    op.drop_table('job_history')
    op.drop_index(op.f('ix_review_decision_workspace_id'), table_name='review_decision')
    op.drop_index(op.f('ix_review_decision_reviewer_id'), table_name='review_decision')
    op.drop_index(op.f('ix_review_decision_lead_id'), table_name='review_decision')
    op.drop_table('review_decision')
    op.drop_index(op.f('ix_review_assignment_workspace_id'), table_name='review_assignment')
    op.drop_index(op.f('ix_review_assignment_reviewer_id'), table_name='review_assignment')
    op.drop_index(op.f('ix_review_assignment_lead_id'), table_name='review_assignment')
    op.drop_table('review_assignment')
    op.drop_index(op.f('ix_outcome_workspace_id'), table_name='outcome')
    op.drop_index(op.f('ix_outcome_lead_id'), table_name='outcome')
    op.drop_table('outcome')
    op.drop_index(op.f('ix_job_workspace_id'), table_name='job')
    op.drop_index(op.f('ix_job_ats_board_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_fact_workspace_id'), table_name='fact')
    op.drop_index(op.f('ix_fact_evidence_record_id'), table_name='fact')
    op.drop_index(op.f('ix_fact_company_id'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_cost_ledger_workspace_id'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index(op.f('ix_suppression_workspace_id'), table_name='suppression')
    op.drop_index(op.f('ix_suppression_company_id'), table_name='suppression')
    op.drop_table('suppression')
    op.drop_index(op.f('ix_lead_assessment_workspace_id'), table_name='lead_assessment')
    op.drop_index(op.f('ix_lead_assessment_company_id'), table_name='lead_assessment')
    op.drop_index(op.f('ix_lead_assessment_campaign_id'), table_name='lead_assessment')
    op.drop_table('lead_assessment')
    op.drop_index(op.f('ix_feature_workspace_id'), table_name='feature')
    op.drop_index(op.f('ix_feature_company_id'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_export_record_workspace_id'), table_name='export_record')
    op.drop_table('export_record')
    op.drop_index(op.f('ix_evidence_record_workspace_id'), table_name='evidence_record')
    op.drop_index(op.f('ix_evidence_record_source_event_id'), table_name='evidence_record')
    op.drop_index(op.f('ix_evidence_record_company_id'), table_name='evidence_record')
    op.drop_table('evidence_record')
    op.drop_index(op.f('ix_discovery_event_workspace_id'), table_name='discovery_event')
    op.drop_index(op.f('ix_discovery_event_campaign_id'), table_name='discovery_event')
    op.drop_table('discovery_event')
    op.drop_index(op.f('ix_contact_route_workspace_id'), table_name='contact_route')
    op.drop_index(op.f('ix_contact_route_company_id'), table_name='contact_route')
    op.drop_table('contact_route')
    op.drop_index(op.f('ix_company_relationship_workspace_id'), table_name='company_relationship')
    op.drop_index(op.f('ix_company_relationship_parent_company_id'), table_name='company_relationship')
    op.drop_index(op.f('ix_company_relationship_child_company_id'), table_name='company_relationship')
    op.drop_table('company_relationship')
    op.drop_index(op.f('ix_company_identifier_workspace_id'), table_name='company_identifier')
    op.drop_index(op.f('ix_company_identifier_company_id'), table_name='company_identifier')
    op.drop_table('company_identifier')
    op.drop_index(op.f('ix_company_alias_workspace_id'), table_name='company_alias')
    op.drop_index(op.f('ix_company_alias_company_id'), table_name='company_alias')
    op.drop_table('company_alias')
    op.drop_index(op.f('ix_classifier_run_workspace_id'), table_name='classifier_run')
    op.drop_index(op.f('ix_classifier_run_company_id'), table_name='classifier_run')
    op.drop_table('classifier_run')
    op.drop_index(op.f('ix_campaign_run_workspace_id'), table_name='campaign_run')
    op.drop_index(op.f('ix_campaign_run_campaign_id'), table_name='campaign_run')
    op.drop_table('campaign_run')
    op.drop_index(op.f('ix_ats_board_workspace_id'), table_name='ats_board')
    op.drop_index(op.f('ix_ats_board_company_id'), table_name='ats_board')
    op.drop_table('ats_board')
    op.drop_index(op.f('ix_source_policy_workspace_id'), table_name='source_policy')
    op.drop_table('source_policy')
    op.drop_index(op.f('ix_source_health_workspace_id'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_source_event_workspace_id'), table_name='source_event')
    op.drop_table('source_event')
    op.drop_index(op.f('ix_scorecard_workspace_id'), table_name='scorecard')
    op.drop_table('scorecard')
    op.drop_index(op.f('ix_page_snapshot_workspace_id'), table_name='page_snapshot')
    op.drop_table('page_snapshot')
    op.drop_index(op.f('ix_operational_metadata_workspace_id'), table_name='operational_metadata')
    op.drop_table('operational_metadata')
    op.drop_index(op.f('ix_membership_workspace_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_jurisdiction_policy_workspace_id'), table_name='jurisdiction_policy')
    op.drop_table('jurisdiction_policy')
    op.drop_index(op.f('ix_company_workspace_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_campaign_workspace_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_audit_event_workspace_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('workspace')
    op.drop_table('user')
    # ### end Alembic commands ###
