"""source hit company link

Revision ID: f3133807f10f
Revises: 18caeb93d261
Create Date: 2026-07-15 23:50:03.736011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3133807f10f'
down_revision: Union[str, Sequence[str], None] = '18caeb93d261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_hit', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_source_hit_company_id'), 'source_hit', ['company_id'], unique=False)
    op.create_foreign_key('fk_source_hit_company', 'source_hit', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_source_hit_company', 'source_hit', type_='foreignkey')
    op.drop_index(op.f('ix_source_hit_company_id'), table_name='source_hit')
    op.drop_column('source_hit', 'company_id')
    # ### end Alembic commands ###
